### ISSUE TITLE
macOS support, Windows support

### ISSUE THREAD

**Issue by ghost** [openSUSE/daps2docker#4]
macOS:

* does not have systemctl
* only has Bash 3 out of the box; maybe rewrite in Python 3 instead (need to check that Python comes with a default macOS install?
* needs fixing of installation instructions

Windows:

* does not have systemctl
* has no Bash whatsoever installed
* has no Python whatsoever installed 
* if we make people install something into WSL, we might as well save ourselves the trouble of using Docker

**Comment by tomschr** [comment]
Not my priority.
